version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:18.16
    working_directory: ~/react-native-bundle-size

commands:
  save-cache-yarn:
    steps:
      - save_cache:
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  restore-cache-yarn:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
  attach-workspace:
    steps:
      - attach_workspace:
          at: ~/react-native-bundle-size

jobs:
  checkout:
    executor: default
    steps:
      - checkout
      - restore-cache-yarn
      - run:
          name: Yarn version
          command: yarn -v
      - run:
          name: Yarn Install
          command: |
            yarn install --frozen-lockfile --no-progress --non-interactive --cache-folder ~/.cache/yarn
      - save-cache-yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    executor: default
    steps:
      - attach-workspace
      - run:
          name: Lint
          command: yarn lint
  type-check:
    executor: default
    steps:
      - attach-workspace
      - run:
          name: Type Check
          command: yarn type-check

workflows:
  tests:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - type-check:
          requires:
            - checkout
